framework:
    workflows: 
        real_estate:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'currentState'
            supports:
                - App\Entity\RealEstate
            initial_marking: brouillon
            places:
                - brouillon
                - complété
                - mandaté
                - proposition
                - engagement
                - vendu
            transitions:
                documenté:
                    from: brouillon
                    to: complété
                négociateur:
                    from: complété
                    to: mandaté
                visité:
                    from: mandaté
                    to: mandaté
                offre:
                    from: mandaté
                    to: proposition
                confirmation:
                    from: proposition
                    to: engagement
                notaire:
                    from: engagement
                    to: vendu
                
                